
function rpropState = initrprop(fnn, deltaMin=0.000001, deltaMax=1)
% Initialize structure containing RPROP algorithm state
%
% usage: rpropState = initrprop(fnn, deltaMin=0.000001, deltaMax=1)
%

	rpropState = struct(...
		'weights1', initrpropstruct(fnn.weights1),...
		'bias1', initrpropstruct(fnn.bias1),...
		'weights2', initrpropstruct(fnn.weights2),...
		'bias2', initrpropstruct(fnn.bias2),...
		'deltaMin', deltaMin,...
		'deltaMax', deltaMax);
end

function rpropStruct = initrpropstruct(weights)
	initialDelta = 0.0001;
	rpropStruct = struct(...
		'errors', zeros(size(weights)),...
		'deltas', ones(size(weights)) .* initialDelta,...
		'weightUpdates', zeros(size(weights)));
end
